### ISSUE TITLE
Installation instructions elm-format

### ISSUE THREAD

**Issue by Brian11f** [mbuscemi/elm-curriculum#1]
I found that you must install atom-beautify after elm-format. I had atom-beautify pre-installed and skipped that step.

**Comment by mbuscemi** [comment]
Interesting. I hadn't used atom-beautify. It worked on my system without me having to tell it where to the find the elm-format executable, so I'm willing to give it a shot. Thanks for the suggestion!

**Comment by mbuscemi** [comment]
I updated the instructions. Let me know if anything can be made clearer.
